<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: someguy
 * Date: Fri, 14 Mar 2025 07:38:43 +0100
 */

$conf['title'] = 'InfoBay';
$conf['start'] = 'Main Page';
$conf['template'] = 'sprintdoc';
$conf['sidebar'] = 'Sidebar';
$conf['license'] = 'cc-by-sa';
$conf['useacl'] = 1;
$conf['superuser'] = '@admin';
$conf['plugin']['gallery']['options'] = 'cache,crop,lightbox';
$conf['tpl']['bootstrap3']['socialShareProviders'] = 'facebook,linkedin,microsoft-teams,pinterest,whatsapp,reddit,twitter,telegram,yammer,google-plus';
