# users.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Userfile
#
# Auto-generated by install script
# Date: Sat, 01 Mar 2025 05:22:45 +0000
#
# Format:
# login:passwordhash:Real Name:email:groups,comma,separated

someguy:$2y$10$cBJgdvsbklQyblVLQYJiQu/VoJ.F4mWI7RBXSpdn9ZvatjvQ.VQ0O:Vincent:vincentnyl08@gmail.com:admin,user
